### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by ryankeener** [bean710/holberton-system_engineering-devops#2]
https://github.com/bean710/holberton-system_engineering-devops/blob/e5f40eb0ea2043d780994be2ee7a5db545b506e9/0x00-shell_basics/15-lets_move#L2
```sh
# shorthand for alphabetic characters
mv [A-Z]* /tmp/u 

# Another option which would work
mv [A-Z]+ /tmp/u
```
Also, this is a very useful tool for testing out and understanding regular expressions: https://regex101.com/

![](https://cl.ly/c8b256207f06/download/Image%2525202019-09-12%252520at%2525209.39.57%252520AM.png)

**Comment by bean710** [comment]
It's glob, which is somehow worse than regex.....
